# Generated by Django 6.0.4 on 2026-09-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='order_id',
        ),
    ]
